import type { Metadata } from "next";
import { Urbanist } from "next/font/google";

import "./globals.scss";
import { CursorProvider } from "./components/context/CursorContext";
import ThemeContextProvider from "./components/context/ThemeContext";
import ThemeSwitch from "./components/ThemeSwitch";
import { TransitionProvider } from "./components/TransitionProvider";
// import ScrollManager from "./components/ScrollManager";
import ReactLenis from "lenis/react";
import ScrollManager from "./components/ScrollManager";
import Head from "next/head";

const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Mathias Ebner - Creative Technologist",
  description: "Generated by create next app",
  keywords: [
    "Web Developer",
    "Frontend Developer",
    "Creative Technologist",
    "Portfolio",
    "Web Projects",
    "UI/UX",
    "Web Design",
    "Mathias Ebner",
    "Photos",
    "Poster Designs",
    "Technology",
    "Personal Website",
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${urbanist.variable} `}>
      <Head>
        {/* Add your PNG favicon */}
        <link
          rel="icon"
          href="/favicon-16x16.png"
          type="image/png"
          sizes="16x16"
        />
        {/* Optionally, you can also add a 32x32 version */}
        <link
          rel="icon"
          href="/favicon-32x32.png"
          type="image/png"
          sizes="32x32"
        />
      </Head>
      <body className={`vsc-initialized font-urbanist antialiased`}>
        <TransitionProvider>
          <ThemeContextProvider>
            {/* <ScrollManager> */}
            <ReactLenis
              root
              options={{
                duration: 2,
                lerp: 0.05,
                // syncTouch: true,
                // syncTouchLerp: 0.1,
                // touchMultiplier: 0,
                // wheelMultiplier: 1.25,
                // syncTouchLerp: 0.99,

                // smoothWheel: true,
              }}
            >
              <CursorProvider>
                <ScrollManager />

                {children}

                <ThemeSwitch />
              </CursorProvider>
            </ReactLenis>
            {/* </ScrollManager> */}
          </ThemeContextProvider>
        </TransitionProvider>
      </body>
    </html>
  );
}
