import type { Metadata } from "next";
// import { Nunito_Sans } from "next/font/google";
// import { Raleway } from "next/font/google";
import { Urbanist } from "next/font/google";

import "./globals.scss";
import { CursorProvider } from "./components/context/CursorContext";
import ThemeContextProvider from "./components/context/ThemeContext";
import ThemeSwitch from "./components/ThemeSwitch";
import { ReactLenis } from "lenis/react";
import { TransitionProvider } from "./components/TransitionProvider";

// const nunitoSans = Nunito_Sans({
//   variable: "--font-nunito-sans",
//   subsets: ["latin"],
//   display: "swap",
// });

// const raleway = Raleway({
//   variable: "--font-raleway",
//   subsets: ["latin"],
//   display: "swap",
// });

const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${urbanist.variable}`}>
      <body className={`vsc-initialized font-urbanist antialiased`}>
        <TransitionProvider>
          <ThemeContextProvider>
            <ReactLenis
              root
              options={{
                lerp: 0.05,
                duration: 2,
              }}
            >
              <CursorProvider>
                {children}
                <ThemeSwitch />
              </CursorProvider>
            </ReactLenis>
          </ThemeContextProvider>
        </TransitionProvider>
      </body>
    </html>
  );
}
